# Generated by Django 5.0.1 on 2024-05-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyurtmaApp', '0001_initial'),
        ('mahsulotApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyurtmamahsulot',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtmaApp.buyurtma'),
        ),
        migrations.AddField(
            model_name='buyurtmamahsulot',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot'),
        ),
        migrations.AddField(
            model_name='savat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savatmahsulot',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot'),
        ),
        migrations.AddField(
            model_name='savatmahsulot',
            name='savat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtmaApp.savat'),
        ),
        migrations.AddField(
            model_name='sevimli',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot'),
        ),
        migrations.AddField(
            model_name='sevimli',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sevimli',
            unique_together={('user', 'mahsulot')},
        ),
    ]
