# Generated by Django 5.0.1 on 2024-05-20 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('sarlavha', models.CharField(max_length=255, unique=True)),
                ('rasm', models.ImageField(upload_to='kataloglar/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('batafsil', models.TextField(blank=True, null=True)),
                ('brend', models.CharField(blank=True, max_length=255)),
                ('dokon', models.CharField(blank=True, max_length=255)),
                ('narx', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chegirma', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('kafolat', models.CharField(blank=True, max_length=255, null=True)),
                ('baho', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='SubKatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='sub-kataloglar/')),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('qiymat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('rasm', models.ImageField(upload_to='mahsulotrasm/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('baho', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)])),
                ('izoh', models.TextField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
