# Generated by Django 5.0.1 on 2024-05-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahsulotApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subkatalog',
            name='katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.katalog'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='subKatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.subkatalog'),
        ),
        migrations.AddField(
            model_name='xususiyat',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulotApp.mahsulot'),
        ),
        migrations.AlterUniqueTogether(
            name='xususiyat',
            unique_together={('qiymat', 'nom')},
        ),
    ]
