# Generated by Django 5.0.1 on 2024-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('batafsil', models.TextField()),
                ('rasm', models.ImageField(upload_to='yangilik/')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
