# Generated by Django 5.0.1 on 2024-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilik',
            name='rasm',
            field=models.ImageField(upload_to='yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
